server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: currency-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/currency-service?useTimeZone=true&serverTimezone=UTC
    username: root
    password: "#!d0D0d0D0d0#!"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: currency-service
    user: root
    password: "#!d0D0d0D0d0#!"
